//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMToolBox.Mail
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVER
    {
        public int ID { get; set; }
        public string IP { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public int PORT { get; set; }
        public bool ENABLE { get; set; }
        public bool SSL { get; set; }
    }
}
